--- 
kind: Service
apiVersion: v1
metadata:
  name: jupyter
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:035612810169:certificate/eafb58f8-9cc3-4d97-afe4-026600c6cd65
spec:
  selector:
    app: jupyter
  type: LoadBalancer
  externalName: navaneethreddydevops.com
  ports:
  - name: web
    port: 443
    targetPort: 9376
    protocol: TCP
  selector:
    app: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jupyter
  template:
    metadata:
      labels:
        name: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/scipy-notebook:abdb27a6dfbb 
      dnsPolicy: ClusterFirst
      restartPolicy: Always