apiVersion: v1
kind: Service
metadata:
  name: web-app
  annotations:
      cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.0.240.120
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.0/0