apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-variables
  namespace: navaneethreddydevops
data:
  HTTP_PROXY: http://navaneethreddydevops.proxy.host:8099
  http_proxy: http://navaneethreddydevops.proxy.host:8099
  HTTPS_PROXY: http://navaneethreddydevops.proxy.host:8099
  https_proxy: http://navaneethreddydevops.proxy.host:8099
  NO_PROXY: 172.20.0.0/16,localhost,127.0.0.1,10.0.0.0/16,169.254.169.254,.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com
  no_proxy: 172.20.0.0/16,localhost,127.0.0.1,10.0.0.0/16,169.254.169.254,.internal,s3.amazonaws.com,.s3.us-east-1.amazonaws.com,api.ecr.us-east-1.amazonaws.com,dkr.ecr.us-east-1.amazonaws.com,ec2.us-east-1.amazonaws.com
