---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-west-2
  version: "1.18"

# Adding the Private VPC subnets
# vpc:
#   subnets:
#     private:
#       eu-north-1a: { id: subnet-0ff156e0c4a6d300c }
#       eu-north-1b: { id: subnet-0549cdab573695c03 }
#       eu-north-1c: { id: subnet-0426fb4a607393184 }

nodeGroups:
  - name: spot-nodegroup
    labels: { role: workers }
    minSize: 1
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh: 
      publicKeyName: 'keypair'
  - name: nodegroup-2
    labels: {role: worker}
    minSize: 1
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh:
      publicKeyName: 'keypair'
    # iam:
    #   withAddonPolicies:
    #     externalDNS: true
    #     certManager: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]