---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-west-2
  version: "1.17"
vpc:
  cidr: "10.0.0.0/16"
nodeGroups:
  - name: spot-nodegroup
    labels: { role: workers }
    minSize: 2
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro","c4.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh:
      publicKeyName: 'keypair'
  - name: nodegroup-2
    labels: {role: worker}
    minSize: 2
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro","c4.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh:
      publicKeyName: 'keypair'
  # - name: nodegroup-3
  #   labels: {role: worker}
  #   minSize: 2
  #   maxSize: 5
  #   instancesDistribution:
  #     maxPrice: 0.017
  #     instanceTypes: ["c4.large"] # At least one instance type should be specified
  #     onDemandBaseCapacity: 0
  #     onDemandPercentageAboveBaseCapacity: 50
  #     spotInstancePools: 2
  #   ssh:
  #     publicKeyName: 'keypair'
  #   # iam:
  #   #   withAddonPolicies:
  #   #     externalDNS: true
  #   #     certManager: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]