---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-fargate
  region: us-west-2
  version: "1.27"
vpc:
  cidr: "10.0.0.0/16"
nodeGroups:
  - name: ng-1
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 1
  - name: ng-2
    labels: { role: workers }
    instanceType: t2.micro
    desiredCapacity: 2
  - name: ng-3
    labels: { role: workers }
    instanceType: t2.micro
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]