---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: learning-cluster
  region: us-west-2

nodeGroups:
  - name: spot-nodegroup
    labels: { role: workers }
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-west-1a"]
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh: 
      publicKeyName: 'keypair'
  - name: nodegroup-2
    labels: {role: worker}
    instanceType: m5.xlarge
    minSize: 1
    maxSize: 3
    availabilityZones: ["us-west-1b"]
    ssh:
      publicKeyName: 'keypair'

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]