---
# HOST-1 Information
host: dallas-2
datacenter : 
  #Mappings
  location: dallas
  cab : 13 
  cab_unit: 3
roles: 
  #Sequences
  - wordpress
  - mysql
downtime_sch : |
  2018-10-31 - kernel upgrade
  2019-02-02 - security fix
comments: > 
  Experiencing high volumes of I/O
  Since 2018-10-31.
  Currently Inverstigation.
--- 
# HOST-2 Information
host: dallas-3
datacenter : 
  location : dallas
  cab : 14
  cab_unit: 3
roles:
  -nodejs
  -mongodb
downtime_sch: |
  2020-10-21 - Monogodb upgrade
  2020-10-22 - TLS upgrade
comments: >
  This is a Upgrade for Mongodb server.
  Scheduled on October month of this Year
...
--- 
# HOST-2 Information
host: helsinki
datacenter : 
  location : helsinki
  cab : 14
  cab_unit: 3
roles:
  - angular
  - mysql
downtime_sch: |
  2020-10-21 - mysql upgrade
  2020-10-22 - TLS upgrade
comments: >
  This is a Upgrade for mysql server.
  Scheduled on October month of this Year
